apiVersion: 'apps/v1'
kind: deployment
metadata:
  name: 'goappdeployment'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'go-web'
  template:
    metadata:
      labels: 
        app: 'go-web'
    spec: 
      containers:
        image: omnagare/go-web-app 
        ports:
          - containerPort: 8080
      
    
      
        
  